Homework 1 – dxy2101
================

``` r
library(tidyverse)
```

    ## ── Attaching packages ─────────────────────────────────────── tidyverse 1.3.2 ──
    ## ✔ ggplot2 3.3.6     ✔ purrr   0.3.4
    ## ✔ tibble  3.1.8     ✔ dplyr   1.0.9
    ## ✔ tidyr   1.2.0     ✔ stringr 1.4.0
    ## ✔ readr   2.1.2     ✔ forcats 0.5.2
    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## ✖ dplyr::filter() masks stats::filter()
    ## ✖ dplyr::lag()    masks stats::lag()

``` r
install.packages("palmerpenguins", repos = "http://cran.us.r-project.org")
```

    ## 
    ## The downloaded binary packages are in
    ##  /var/folders/1p/9yn7b9k529j149ntzd2ng2sw0000gn/T//Rtmpfv8L43/downloaded_packages

# Problem 1

### Load and describe `penguins` dataset.

``` r
data("penguins", package = "palmerpenguins")

# List variables in dataset
names(penguins)
```

    ## [1] "species"           "island"            "bill_length_mm"   
    ## [4] "bill_depth_mm"     "flipper_length_mm" "body_mass_g"      
    ## [7] "sex"               "year"

``` r
# Size of dataset
nrow(penguins)
```

    ## [1] 344

``` r
ncol(penguins)
```

    ## [1] 8

``` r
# Calculate mean flipper length
mean(penguins$flipper_length_mm, na.rm=TRUE)
```

    ## [1] 200.9152

The `penguins` dataset includes 8 variables describing a sample of 344
individual penguins. This dataset may be useful for understanding the
different compositions of different penguin species across
e.g. geographies, years, sex, and among the physical attributes
themselves.

The following variables are included: \* species \* island of origin \*
bill length (mm) \* bill depth (mm) \* flipper length (mm) \* body mass
(g) \* sex \* year data was collected

From `penguins`, we found that the mean flipper length, excluding
missing values, is 200.9152 mm.

### Create scatterplot for flipper length and bill length

``` r
# Create a dataframe containing variables for the plot
plot_df = tibble(
  x = penguins$bill_length_mm,
  y = penguins$flipper_length_mm
)

# Create scatter plot with colors indicating species type
Species = penguins$species

ggplot(plot_df, aes(x=x, y=y, color=Species)) + geom_point()
```

    ## Warning: Removed 2 rows containing missing values (geom_point).

![](dxy2101_hw1_P8105_files/figure-gfm/scatterplot-1.png)<!-- -->

``` r
# Export scatter plot
ggsave("bill_flipper_plot.pdf", height = 4, width = 6)
```

    ## Warning: Removed 2 rows containing missing values (geom_point).
